### PR TITLE
Allow for arrow >= 1.0.2 on Python 3.6+

### PR DESCRIPTION
**Pull request by sigmavirus24**
Closes https://github.com/Backblaze/b2-sdk-python/issues/201

### CODE REVIEW

**Review by mlech-reef — CHANGES_REQUESTED** [review]
Please update the changelog

**Comment by sigmavirus24** [comment]
> Please update the changelog

Done

**Review by mlech-reef — APPROVED** [review]

**Comment by ppolewicz** [comment]
CI after merge will confirm if it works

**Comment by sigmavirus24** [comment]
Thanks @mlech-reef and @ppolewicz !

**Pull request merged**
