### PR TITLE
Add support for XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by mpnowacki-reef**
replaces https://github.com/Backblaze/b2-sdk-python/pull/129

### CODE REVIEW

**Review by mzukowski-reef — APPROVED** [review]

**Review by ppolewicz — APPROVED** [review]
it's beautiful

**Comment by ppolewicz** [comment]
on a side note, @mpnowacki-reef shoudln't we schedule removal of everything that starts with `os.path.` in favor of `pathlib`? Maybe add that to the list of things we can do when dropping 3.5?

**Comment by mpnowacki-reef** [comment]
@ppolewicz Yes we could, but pathlib was introduced in 3.4, so i guess there's no need for it to happen only when dropping 3.5, right?

**Comment by ppolewicz** [comment]
that is true, but we missed it back then, so now we track it in https://github.com/Backblaze/b2-sdk-python/issues/239 to not forget

**Pull request merged**
